/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Accounts: () => import('#controllers/accounts_controller'),
  Admin: () => import('#controllers/admin_controller'),
  ApiKeys: () => import('#controllers/api_keys_controller'),
  Applications: () => import('#controllers/applications_controller'),
  AuditLogs: () => import('#controllers/audit_logs_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Commissions: () => import('#controllers/commissions_controller'),
  Countries: () => import('#controllers/countries_controller'),
  Currencies: () => import('#controllers/currencies_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  LedgerEntries: () => import('#controllers/ledger_entries_controller'),
  MobileOperators: () => import('#controllers/mobile_operators_controller'),
  Monitoring: () => import('#controllers/monitoring_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  OperatorPrefixes: () => import('#controllers/operator_prefixes_controller'),
  ProviderRoutes: () => import('#controllers/provider_routes_controller'),
  Providers: () => import('#controllers/providers_controller'),
  Reconciliation: () => import('#controllers/reconciliation_controller'),
  Routing: () => import('#controllers/routing_controller'),
  Session: () => import('#controllers/session_controller'),
  Transactions: () => import('#controllers/transactions_controller'),
  Users: () => import('#controllers/users_controller'),
  Webhooks: () => import('#controllers/webhooks_controller'),
}
