/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccountSchema extends BaseModel {
  static $columns = ['accountType', 'applicationId', 'balanceCached', 'createdAt', 'currency', 'id', 'updatedAt'] as const
  $columns = AccountSchema.$columns
  @column()
  declare accountType: string
  @column()
  declare applicationId: string
  @column()
  declare balanceCached: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ApiKeySchema extends BaseModel {
  static $columns = ['applicationId', 'createdAt', 'expiresAt', 'id', 'keyHash', 'keyType', 'lastUsedAt', 'name', 'permissions', 'revokedAt'] as const
  $columns = ApiKeySchema.$columns
  @column()
  declare applicationId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare keyHash: string
  @column()
  declare keyType: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare permissions: any
  @column.dateTime()
  declare revokedAt: DateTime | null
}

export class ApplicationProviderSchema extends BaseModel {
  static $columns = ['applicationId', 'config', 'createdAt', 'environment', 'id', 'isEnabled', 'providerId', 'updatedAt'] as const
  $columns = ApplicationProviderSchema.$columns
  @column()
  declare applicationId: string
  @column()
  declare config: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare environment: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isEnabled: boolean
  @column()
  declare providerId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ApplicationSchema extends BaseModel {
  static $columns = ['createdAt', 'environment', 'id', 'name', 'slug', 'status', 'updatedAt'] as const
  $columns = ApplicationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare environment: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'applicationId', 'createdAt', 'entityId', 'entityType', 'id', 'ipAddress', 'newValue', 'oldValue', 'userAgent', 'userId'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare applicationId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: string
  @column()
  declare entityType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string
  @column()
  declare newValue: any | null
  @column()
  declare oldValue: any | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string | null
}

export class CommissionSchema extends BaseModel {
  static $columns = ['applicationId', 'countryCode', 'createdAt', 'currencyCode', 'id', 'maxAmount', 'minAmount', 'mobileOperatorId', 'providerId', 'type', 'updatedAt', 'value'] as const
  $columns = CommissionSchema.$columns
  @column()
  declare applicationId: string | null
  @column()
  declare countryCode: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currencyCode: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare maxAmount: string | null
  @column()
  declare minAmount: string | null
  @column()
  declare mobileOperatorId: string | null
  @column()
  declare providerId: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare value: string
}

export class CountrySchema extends BaseModel {
  static $columns = ['applicationId', 'code', 'createdAt', 'currencyCode', 'id', 'name', 'phonePrefix', 'updatedAt'] as const
  $columns = CountrySchema.$columns
  @column()
  declare applicationId: string
  @column()
  declare code: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currencyCode: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare phonePrefix: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CurrencySchema extends BaseModel {
  static $columns = ['applicationId', 'code', 'createdAt', 'decimals', 'id', 'isActive', 'name', 'symbol'] as const
  $columns = CurrencySchema.$columns
  @column()
  declare applicationId: string
  @column()
  declare code: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare decimals: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare symbol: string
}

export class LedgerEntrySchema extends BaseModel {
  static $columns = ['accountId', 'amount', 'createdAt', 'currency', 'direction', 'id', 'transactionId'] as const
  $columns = LedgerEntrySchema.$columns
  @column()
  declare accountId: string
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare direction: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare transactionId: string
}

export class MobileOperatorSchema extends BaseModel {
  static $columns = ['applicationId', 'countryCode', 'createdAt', 'id', 'isEnabled', 'logoUrl', 'name', 'updatedAt'] as const
  $columns = MobileOperatorSchema.$columns
  @column()
  declare applicationId: string
  @column()
  declare countryCode: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isEnabled: boolean
  @column()
  declare logoUrl: string | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OperatorPrefixSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'mobileOperatorId', 'prefix'] as const
  $columns = OperatorPrefixSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mobileOperatorId: string
  @column()
  declare prefix: string
}

export class ProviderCountrySchema extends BaseModel {
  static $columns = ['applicationId', 'countryId', 'createdAt', 'id', 'providerId', 'updatedAt'] as const
  $columns = ProviderCountrySchema.$columns
  @column()
  declare applicationId: string
  @column()
  declare countryId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare providerId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProviderRouteSchema extends BaseModel {
  static $columns = ['applicationId', 'createdAt', 'id', 'isActive', 'mobileOperatorId', 'priority', 'providerId', 'updatedAt'] as const
  $columns = ProviderRouteSchema.$columns
  @column()
  declare applicationId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare mobileOperatorId: string
  @column()
  declare priority: number
  @column()
  declare providerId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProviderSchema extends BaseModel {
  static $columns = ['code', 'config', 'createdAt', 'description', 'icon', 'id', 'label', 'name', 'status', 'type', 'updatedAt'] as const
  $columns = ProviderSchema.$columns
  @column()
  declare code: string
  @column()
  declare config: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare label: string | null
  @column()
  declare name: string
  @column()
  declare status: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ReconciliationEntrySchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'currency', 'externalRef', 'id', 'matchedAt', 'metadata', 'source', 'status', 'transactionId'] as const
  $columns = ReconciliationEntrySchema.$columns
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare externalRef: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare matchedAt: DateTime | null
  @column()
  declare metadata: any
  @column()
  declare source: string
  @column()
  declare status: string
  @column()
  declare transactionId: string | null
}

export class TransactionEventSchema extends BaseModel {
  static $columns = ['createdAt', 'fromStatus', 'id', 'payload', 'toStatus', 'transactionId'] as const
  $columns = TransactionEventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fromStatus: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare payload: any
  @column()
  declare toStatus: string
  @column()
  declare transactionId: string
}

export class TransactionSchema extends BaseModel {
  static $columns = ['amount', 'applicationId', 'createdAt', 'currency', 'errorMessage', 'fxRate', 'id', 'idempotencyKey', 'metadata', 'mobileOperatorId', 'msisdn', 'providerId', 'providerRef', 'providerRouteId', 'reference', 'status', 'txType', 'updatedAt'] as const
  $columns = TransactionSchema.$columns
  @column()
  declare amount: string
  @column()
  declare applicationId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare errorMessage: string | null
  @column()
  declare fxRate: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare idempotencyKey: string
  @column()
  declare metadata: any
  @column()
  declare mobileOperatorId: string | null
  @column()
  declare msisdn: string
  @column()
  declare providerId: string | null
  @column()
  declare providerRef: string | null
  @column()
  declare providerRouteId: string | null
  @column()
  declare reference: string
  @column()
  declare status: string
  @column()
  declare txType: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['applicationId', 'createdAt', 'email', 'id', 'name', 'password', 'role', 'status', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare applicationId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class WebhookDeliverySchema extends BaseModel {
  static $columns = ['attempts', 'createdAt', 'event', 'id', 'lastAttemptAt', 'payload', 'responseBody', 'responseStatus', 'status', 'webhookId'] as const
  $columns = WebhookDeliverySchema.$columns
  @column()
  declare attempts: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare event: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastAttemptAt: DateTime | null
  @column()
  declare payload: any
  @column()
  declare responseBody: string | null
  @column()
  declare responseStatus: number | null
  @column()
  declare status: string
  @column()
  declare webhookId: string
}

export class WebhookSchema extends BaseModel {
  static $columns = ['applicationId', 'createdAt', 'events', 'id', 'secretHash', 'status', 'updatedAt', 'url'] as const
  $columns = WebhookSchema.$columns
  @column()
  declare applicationId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare events: any
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare secretHash: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare url: string
}
