/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type ApiKeyTransformer from '#transformers/api_key_transformer'
import type ApplicationTransformer from '#transformers/application_transformer'
import type CountryTransformer from '#transformers/country_transformer'
import type MobileOperatorTransformer from '#transformers/mobile_operator_transformer'
import type OperatorPrefixTransformer from '#transformers/operator_prefix_transformer'
import type ProviderRouteTransformer from '#transformers/provider_route_transformer'
import type ProviderTransformer from '#transformers/provider_transformer'
import type TransactionTransformer from '#transformers/transaction_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type ApiKey = InferData<ApiKeyTransformer>
  export namespace ApiKey {
    export type Variants = InferVariants<ApiKeyTransformer>
  }
  export type Application = InferData<ApplicationTransformer>
  export namespace Application {
    export type Variants = InferVariants<ApplicationTransformer>
  }
  export type Country = InferData<CountryTransformer>
  export namespace Country {
    export type Variants = InferVariants<CountryTransformer>
  }
  export type MobileOperator = InferData<MobileOperatorTransformer>
  export namespace MobileOperator {
    export type Variants = InferVariants<MobileOperatorTransformer>
  }
  export type OperatorPrefix = InferData<OperatorPrefixTransformer>
  export namespace OperatorPrefix {
    export type Variants = InferVariants<OperatorPrefixTransformer>
  }
  export type ProviderRoute = InferData<ProviderRouteTransformer>
  export namespace ProviderRoute {
    export type Variants = InferVariants<ProviderRouteTransformer>
  }
  export type Provider = InferData<ProviderTransformer>
  export namespace Provider {
    export type Variants = InferVariants<ProviderTransformer>
  }
  export type Transaction = InferData<TransactionTransformer>
  export namespace Transaction {
    export type Variants = InferVariants<TransactionTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
