/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'home': {
    methods: ["GET","HEAD"],
    pattern: '/',
    tokens: [{"old":"/","type":0,"val":"/","end":""}],
    types: placeholder as Registry['home']['types'],
  },
  'auth.register': {
    methods: ["POST"],
    pattern: '/api/v1/auth/register',
    tokens: [{"old":"/api/v1/auth/register","type":0,"val":"api","end":""},{"old":"/api/v1/auth/register","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/register","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['auth.register']['types'],
  },
  'auth.login': {
    methods: ["POST"],
    pattern: '/api/v1/auth/login',
    tokens: [{"old":"/api/v1/auth/login","type":0,"val":"api","end":""},{"old":"/api/v1/auth/login","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/login","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.login']['types'],
  },
  'auth.refresh': {
    methods: ["POST"],
    pattern: '/api/v1/auth/refresh',
    tokens: [{"old":"/api/v1/auth/refresh","type":0,"val":"api","end":""},{"old":"/api/v1/auth/refresh","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/refresh","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/refresh","type":0,"val":"refresh","end":""}],
    types: placeholder as Registry['auth.refresh']['types'],
  },
  'auth.me': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/auth/me',
    tokens: [{"old":"/api/v1/auth/me","type":0,"val":"api","end":""},{"old":"/api/v1/auth/me","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/me","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['auth.me']['types'],
  },
  'auth.logout': {
    methods: ["POST"],
    pattern: '/api/v1/auth/logout',
    tokens: [{"old":"/api/v1/auth/logout","type":0,"val":"api","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['auth.logout']['types'],
  },
  'dashboard.get_stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/dashboard/stats',
    tokens: [{"old":"/api/v1/dashboard/stats","type":0,"val":"api","end":""},{"old":"/api/v1/dashboard/stats","type":0,"val":"v1","end":""},{"old":"/api/v1/dashboard/stats","type":0,"val":"dashboard","end":""},{"old":"/api/v1/dashboard/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['dashboard.get_stats']['types'],
  },
  'applications.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/applications',
    tokens: [{"old":"/api/v1/applications","type":0,"val":"api","end":""},{"old":"/api/v1/applications","type":0,"val":"v1","end":""},{"old":"/api/v1/applications","type":0,"val":"applications","end":""}],
    types: placeholder as Registry['applications.index']['types'],
  },
  'applications.store': {
    methods: ["POST"],
    pattern: '/api/v1/applications',
    tokens: [{"old":"/api/v1/applications","type":0,"val":"api","end":""},{"old":"/api/v1/applications","type":0,"val":"v1","end":""},{"old":"/api/v1/applications","type":0,"val":"applications","end":""}],
    types: placeholder as Registry['applications.store']['types'],
  },
  'applications.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/applications/:id',
    tokens: [{"old":"/api/v1/applications/:id","type":0,"val":"api","end":""},{"old":"/api/v1/applications/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/applications/:id","type":0,"val":"applications","end":""},{"old":"/api/v1/applications/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['applications.show']['types'],
  },
  'applications.update': {
    methods: ["PUT"],
    pattern: '/api/v1/applications/:id',
    tokens: [{"old":"/api/v1/applications/:id","type":0,"val":"api","end":""},{"old":"/api/v1/applications/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/applications/:id","type":0,"val":"applications","end":""},{"old":"/api/v1/applications/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['applications.update']['types'],
  },
  'applications.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/applications/:id',
    tokens: [{"old":"/api/v1/applications/:id","type":0,"val":"api","end":""},{"old":"/api/v1/applications/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/applications/:id","type":0,"val":"applications","end":""},{"old":"/api/v1/applications/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['applications.destroy']['types'],
  },
  'applications.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/applications/:id/stats',
    tokens: [{"old":"/api/v1/applications/:id/stats","type":0,"val":"api","end":""},{"old":"/api/v1/applications/:id/stats","type":0,"val":"v1","end":""},{"old":"/api/v1/applications/:id/stats","type":0,"val":"applications","end":""},{"old":"/api/v1/applications/:id/stats","type":1,"val":"id","end":""},{"old":"/api/v1/applications/:id/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['applications.stats']['types'],
  },
  'api_keys.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/applications/:application_id/api-keys',
    tokens: [{"old":"/api/v1/applications/:application_id/api-keys","type":0,"val":"api","end":""},{"old":"/api/v1/applications/:application_id/api-keys","type":0,"val":"v1","end":""},{"old":"/api/v1/applications/:application_id/api-keys","type":0,"val":"applications","end":""},{"old":"/api/v1/applications/:application_id/api-keys","type":1,"val":"application_id","end":""},{"old":"/api/v1/applications/:application_id/api-keys","type":0,"val":"api-keys","end":""}],
    types: placeholder as Registry['api_keys.index']['types'],
  },
  'api_keys.store': {
    methods: ["POST"],
    pattern: '/api/v1/applications/:application_id/api-keys',
    tokens: [{"old":"/api/v1/applications/:application_id/api-keys","type":0,"val":"api","end":""},{"old":"/api/v1/applications/:application_id/api-keys","type":0,"val":"v1","end":""},{"old":"/api/v1/applications/:application_id/api-keys","type":0,"val":"applications","end":""},{"old":"/api/v1/applications/:application_id/api-keys","type":1,"val":"application_id","end":""},{"old":"/api/v1/applications/:application_id/api-keys","type":0,"val":"api-keys","end":""}],
    types: placeholder as Registry['api_keys.store']['types'],
  },
  'api_keys.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/applications/:application_id/api-keys/:id',
    tokens: [{"old":"/api/v1/applications/:application_id/api-keys/:id","type":0,"val":"api","end":""},{"old":"/api/v1/applications/:application_id/api-keys/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/applications/:application_id/api-keys/:id","type":0,"val":"applications","end":""},{"old":"/api/v1/applications/:application_id/api-keys/:id","type":1,"val":"application_id","end":""},{"old":"/api/v1/applications/:application_id/api-keys/:id","type":0,"val":"api-keys","end":""},{"old":"/api/v1/applications/:application_id/api-keys/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api_keys.show']['types'],
  },
  'api_keys.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/applications/:application_id/api-keys/:id',
    tokens: [{"old":"/api/v1/applications/:application_id/api-keys/:id","type":0,"val":"api","end":""},{"old":"/api/v1/applications/:application_id/api-keys/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/applications/:application_id/api-keys/:id","type":0,"val":"applications","end":""},{"old":"/api/v1/applications/:application_id/api-keys/:id","type":1,"val":"application_id","end":""},{"old":"/api/v1/applications/:application_id/api-keys/:id","type":0,"val":"api-keys","end":""},{"old":"/api/v1/applications/:application_id/api-keys/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api_keys.destroy']['types'],
  },
  'operator_prefixes.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/mobile-operators/:mobile_operator_id/prefixes',
    tokens: [{"old":"/api/v1/mobile-operators/:mobile_operator_id/prefixes","type":0,"val":"api","end":""},{"old":"/api/v1/mobile-operators/:mobile_operator_id/prefixes","type":0,"val":"v1","end":""},{"old":"/api/v1/mobile-operators/:mobile_operator_id/prefixes","type":0,"val":"mobile-operators","end":""},{"old":"/api/v1/mobile-operators/:mobile_operator_id/prefixes","type":1,"val":"mobile_operator_id","end":""},{"old":"/api/v1/mobile-operators/:mobile_operator_id/prefixes","type":0,"val":"prefixes","end":""}],
    types: placeholder as Registry['operator_prefixes.index']['types'],
  },
  'operator_prefixes.store': {
    methods: ["POST"],
    pattern: '/api/v1/mobile-operators/:mobile_operator_id/prefixes',
    tokens: [{"old":"/api/v1/mobile-operators/:mobile_operator_id/prefixes","type":0,"val":"api","end":""},{"old":"/api/v1/mobile-operators/:mobile_operator_id/prefixes","type":0,"val":"v1","end":""},{"old":"/api/v1/mobile-operators/:mobile_operator_id/prefixes","type":0,"val":"mobile-operators","end":""},{"old":"/api/v1/mobile-operators/:mobile_operator_id/prefixes","type":1,"val":"mobile_operator_id","end":""},{"old":"/api/v1/mobile-operators/:mobile_operator_id/prefixes","type":0,"val":"prefixes","end":""}],
    types: placeholder as Registry['operator_prefixes.store']['types'],
  },
  'operator_prefixes.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/mobile-operators/:mobile_operator_id/prefixes/:id',
    tokens: [{"old":"/api/v1/mobile-operators/:mobile_operator_id/prefixes/:id","type":0,"val":"api","end":""},{"old":"/api/v1/mobile-operators/:mobile_operator_id/prefixes/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/mobile-operators/:mobile_operator_id/prefixes/:id","type":0,"val":"mobile-operators","end":""},{"old":"/api/v1/mobile-operators/:mobile_operator_id/prefixes/:id","type":1,"val":"mobile_operator_id","end":""},{"old":"/api/v1/mobile-operators/:mobile_operator_id/prefixes/:id","type":0,"val":"prefixes","end":""},{"old":"/api/v1/mobile-operators/:mobile_operator_id/prefixes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['operator_prefixes.destroy']['types'],
  },
  'transactions.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/transactions',
    tokens: [{"old":"/api/v1/transactions","type":0,"val":"api","end":""},{"old":"/api/v1/transactions","type":0,"val":"v1","end":""},{"old":"/api/v1/transactions","type":0,"val":"transactions","end":""}],
    types: placeholder as Registry['transactions.index']['types'],
  },
  'transactions.store': {
    methods: ["POST"],
    pattern: '/api/v1/transactions',
    tokens: [{"old":"/api/v1/transactions","type":0,"val":"api","end":""},{"old":"/api/v1/transactions","type":0,"val":"v1","end":""},{"old":"/api/v1/transactions","type":0,"val":"transactions","end":""}],
    types: placeholder as Registry['transactions.store']['types'],
  },
  'transactions.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/transactions/:id',
    tokens: [{"old":"/api/v1/transactions/:id","type":0,"val":"api","end":""},{"old":"/api/v1/transactions/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/transactions/:id","type":0,"val":"transactions","end":""},{"old":"/api/v1/transactions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['transactions.show']['types'],
  },
  'transactions.retry': {
    methods: ["POST"],
    pattern: '/api/v1/transactions/:id/retry',
    tokens: [{"old":"/api/v1/transactions/:id/retry","type":0,"val":"api","end":""},{"old":"/api/v1/transactions/:id/retry","type":0,"val":"v1","end":""},{"old":"/api/v1/transactions/:id/retry","type":0,"val":"transactions","end":""},{"old":"/api/v1/transactions/:id/retry","type":1,"val":"id","end":""},{"old":"/api/v1/transactions/:id/retry","type":0,"val":"retry","end":""}],
    types: placeholder as Registry['transactions.retry']['types'],
  },
  'transactions.cancel': {
    methods: ["POST"],
    pattern: '/api/v1/transactions/:id/cancel',
    tokens: [{"old":"/api/v1/transactions/:id/cancel","type":0,"val":"api","end":""},{"old":"/api/v1/transactions/:id/cancel","type":0,"val":"v1","end":""},{"old":"/api/v1/transactions/:id/cancel","type":0,"val":"transactions","end":""},{"old":"/api/v1/transactions/:id/cancel","type":1,"val":"id","end":""},{"old":"/api/v1/transactions/:id/cancel","type":0,"val":"cancel","end":""}],
    types: placeholder as Registry['transactions.cancel']['types'],
  },
  'transactions.export_csv': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/transactions/export/csv',
    tokens: [{"old":"/api/v1/transactions/export/csv","type":0,"val":"api","end":""},{"old":"/api/v1/transactions/export/csv","type":0,"val":"v1","end":""},{"old":"/api/v1/transactions/export/csv","type":0,"val":"transactions","end":""},{"old":"/api/v1/transactions/export/csv","type":0,"val":"export","end":""},{"old":"/api/v1/transactions/export/csv","type":0,"val":"csv","end":""}],
    types: placeholder as Registry['transactions.export_csv']['types'],
  },
  'webhooks.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/webhooks',
    tokens: [{"old":"/api/v1/webhooks","type":0,"val":"api","end":""},{"old":"/api/v1/webhooks","type":0,"val":"v1","end":""},{"old":"/api/v1/webhooks","type":0,"val":"webhooks","end":""}],
    types: placeholder as Registry['webhooks.index']['types'],
  },
  'webhooks.store': {
    methods: ["POST"],
    pattern: '/api/v1/webhooks',
    tokens: [{"old":"/api/v1/webhooks","type":0,"val":"api","end":""},{"old":"/api/v1/webhooks","type":0,"val":"v1","end":""},{"old":"/api/v1/webhooks","type":0,"val":"webhooks","end":""}],
    types: placeholder as Registry['webhooks.store']['types'],
  },
  'webhooks.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/webhooks/:id',
    tokens: [{"old":"/api/v1/webhooks/:id","type":0,"val":"api","end":""},{"old":"/api/v1/webhooks/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/webhooks/:id","type":0,"val":"webhooks","end":""},{"old":"/api/v1/webhooks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['webhooks.show']['types'],
  },
  'webhooks.update': {
    methods: ["PUT"],
    pattern: '/api/v1/webhooks/:id',
    tokens: [{"old":"/api/v1/webhooks/:id","type":0,"val":"api","end":""},{"old":"/api/v1/webhooks/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/webhooks/:id","type":0,"val":"webhooks","end":""},{"old":"/api/v1/webhooks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['webhooks.update']['types'],
  },
  'webhooks.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/webhooks/:id',
    tokens: [{"old":"/api/v1/webhooks/:id","type":0,"val":"api","end":""},{"old":"/api/v1/webhooks/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/webhooks/:id","type":0,"val":"webhooks","end":""},{"old":"/api/v1/webhooks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['webhooks.destroy']['types'],
  },
  'webhooks.deliveries': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/webhooks/:id/deliveries',
    tokens: [{"old":"/api/v1/webhooks/:id/deliveries","type":0,"val":"api","end":""},{"old":"/api/v1/webhooks/:id/deliveries","type":0,"val":"v1","end":""},{"old":"/api/v1/webhooks/:id/deliveries","type":0,"val":"webhooks","end":""},{"old":"/api/v1/webhooks/:id/deliveries","type":1,"val":"id","end":""},{"old":"/api/v1/webhooks/:id/deliveries","type":0,"val":"deliveries","end":""}],
    types: placeholder as Registry['webhooks.deliveries']['types'],
  },
  'webhooks.retry_delivery': {
    methods: ["POST"],
    pattern: '/api/v1/webhooks/:id/deliveries/:delivery_id/retry',
    tokens: [{"old":"/api/v1/webhooks/:id/deliveries/:delivery_id/retry","type":0,"val":"api","end":""},{"old":"/api/v1/webhooks/:id/deliveries/:delivery_id/retry","type":0,"val":"v1","end":""},{"old":"/api/v1/webhooks/:id/deliveries/:delivery_id/retry","type":0,"val":"webhooks","end":""},{"old":"/api/v1/webhooks/:id/deliveries/:delivery_id/retry","type":1,"val":"id","end":""},{"old":"/api/v1/webhooks/:id/deliveries/:delivery_id/retry","type":0,"val":"deliveries","end":""},{"old":"/api/v1/webhooks/:id/deliveries/:delivery_id/retry","type":1,"val":"delivery_id","end":""},{"old":"/api/v1/webhooks/:id/deliveries/:delivery_id/retry","type":0,"val":"retry","end":""}],
    types: placeholder as Registry['webhooks.retry_delivery']['types'],
  },
  'commissions.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/commissions',
    tokens: [{"old":"/api/v1/commissions","type":0,"val":"api","end":""},{"old":"/api/v1/commissions","type":0,"val":"v1","end":""},{"old":"/api/v1/commissions","type":0,"val":"commissions","end":""}],
    types: placeholder as Registry['commissions.index']['types'],
  },
  'commissions.store': {
    methods: ["POST"],
    pattern: '/api/v1/commissions',
    tokens: [{"old":"/api/v1/commissions","type":0,"val":"api","end":""},{"old":"/api/v1/commissions","type":0,"val":"v1","end":""},{"old":"/api/v1/commissions","type":0,"val":"commissions","end":""}],
    types: placeholder as Registry['commissions.store']['types'],
  },
  'commissions.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/commissions/:id',
    tokens: [{"old":"/api/v1/commissions/:id","type":0,"val":"api","end":""},{"old":"/api/v1/commissions/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/commissions/:id","type":0,"val":"commissions","end":""},{"old":"/api/v1/commissions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['commissions.show']['types'],
  },
  'commissions.update': {
    methods: ["PUT"],
    pattern: '/api/v1/commissions/:id',
    tokens: [{"old":"/api/v1/commissions/:id","type":0,"val":"api","end":""},{"old":"/api/v1/commissions/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/commissions/:id","type":0,"val":"commissions","end":""},{"old":"/api/v1/commissions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['commissions.update']['types'],
  },
  'commissions.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/commissions/:id',
    tokens: [{"old":"/api/v1/commissions/:id","type":0,"val":"api","end":""},{"old":"/api/v1/commissions/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/commissions/:id","type":0,"val":"commissions","end":""},{"old":"/api/v1/commissions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['commissions.destroy']['types'],
  },
  'audit_logs.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/audit-logs',
    tokens: [{"old":"/api/v1/audit-logs","type":0,"val":"api","end":""},{"old":"/api/v1/audit-logs","type":0,"val":"v1","end":""},{"old":"/api/v1/audit-logs","type":0,"val":"audit-logs","end":""}],
    types: placeholder as Registry['audit_logs.index']['types'],
  },
  'audit_logs.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/audit-logs/:id',
    tokens: [{"old":"/api/v1/audit-logs/:id","type":0,"val":"api","end":""},{"old":"/api/v1/audit-logs/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/audit-logs/:id","type":0,"val":"audit-logs","end":""},{"old":"/api/v1/audit-logs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['audit_logs.show']['types'],
  },
  'providers.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/providers',
    tokens: [{"old":"/api/v1/providers","type":0,"val":"api","end":""},{"old":"/api/v1/providers","type":0,"val":"v1","end":""},{"old":"/api/v1/providers","type":0,"val":"providers","end":""}],
    types: placeholder as Registry['providers.index']['types'],
  },
  'providers.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/providers/:id',
    tokens: [{"old":"/api/v1/providers/:id","type":0,"val":"api","end":""},{"old":"/api/v1/providers/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/providers/:id","type":0,"val":"providers","end":""},{"old":"/api/v1/providers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['providers.show']['types'],
  },
  'providers.update': {
    methods: ["PUT"],
    pattern: '/api/v1/providers/:id',
    tokens: [{"old":"/api/v1/providers/:id","type":0,"val":"api","end":""},{"old":"/api/v1/providers/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/providers/:id","type":0,"val":"providers","end":""},{"old":"/api/v1/providers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['providers.update']['types'],
  },
  'providers.test_connection': {
    methods: ["POST"],
    pattern: '/api/v1/providers/:id/test',
    tokens: [{"old":"/api/v1/providers/:id/test","type":0,"val":"api","end":""},{"old":"/api/v1/providers/:id/test","type":0,"val":"v1","end":""},{"old":"/api/v1/providers/:id/test","type":0,"val":"providers","end":""},{"old":"/api/v1/providers/:id/test","type":1,"val":"id","end":""},{"old":"/api/v1/providers/:id/test","type":0,"val":"test","end":""}],
    types: placeholder as Registry['providers.test_connection']['types'],
  },
  'providers.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/providers/:id/stats',
    tokens: [{"old":"/api/v1/providers/:id/stats","type":0,"val":"api","end":""},{"old":"/api/v1/providers/:id/stats","type":0,"val":"v1","end":""},{"old":"/api/v1/providers/:id/stats","type":0,"val":"providers","end":""},{"old":"/api/v1/providers/:id/stats","type":1,"val":"id","end":""},{"old":"/api/v1/providers/:id/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['providers.stats']['types'],
  },
  'users.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/users',
    tokens: [{"old":"/api/v1/users","type":0,"val":"api","end":""},{"old":"/api/v1/users","type":0,"val":"v1","end":""},{"old":"/api/v1/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['users.index']['types'],
  },
  'users.store': {
    methods: ["POST"],
    pattern: '/api/v1/users',
    tokens: [{"old":"/api/v1/users","type":0,"val":"api","end":""},{"old":"/api/v1/users","type":0,"val":"v1","end":""},{"old":"/api/v1/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['users.store']['types'],
  },
  'users.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/users/:id',
    tokens: [{"old":"/api/v1/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['users.show']['types'],
  },
  'users.update': {
    methods: ["PUT"],
    pattern: '/api/v1/users/:id',
    tokens: [{"old":"/api/v1/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['users.update']['types'],
  },
  'users.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/users/:id',
    tokens: [{"old":"/api/v1/users/:id","type":0,"val":"api","end":""},{"old":"/api/v1/users/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/users/:id","type":0,"val":"users","end":""},{"old":"/api/v1/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['users.destroy']['types'],
  },
  'users.suspend': {
    methods: ["PATCH"],
    pattern: '/api/v1/users/:id/suspend',
    tokens: [{"old":"/api/v1/users/:id/suspend","type":0,"val":"api","end":""},{"old":"/api/v1/users/:id/suspend","type":0,"val":"v1","end":""},{"old":"/api/v1/users/:id/suspend","type":0,"val":"users","end":""},{"old":"/api/v1/users/:id/suspend","type":1,"val":"id","end":""},{"old":"/api/v1/users/:id/suspend","type":0,"val":"suspend","end":""}],
    types: placeholder as Registry['users.suspend']['types'],
  },
  'users.activate': {
    methods: ["PATCH"],
    pattern: '/api/v1/users/:id/activate',
    tokens: [{"old":"/api/v1/users/:id/activate","type":0,"val":"api","end":""},{"old":"/api/v1/users/:id/activate","type":0,"val":"v1","end":""},{"old":"/api/v1/users/:id/activate","type":0,"val":"users","end":""},{"old":"/api/v1/users/:id/activate","type":1,"val":"id","end":""},{"old":"/api/v1/users/:id/activate","type":0,"val":"activate","end":""}],
    types: placeholder as Registry['users.activate']['types'],
  },
  'accounts.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/accounts',
    tokens: [{"old":"/api/v1/accounts","type":0,"val":"api","end":""},{"old":"/api/v1/accounts","type":0,"val":"v1","end":""},{"old":"/api/v1/accounts","type":0,"val":"accounts","end":""}],
    types: placeholder as Registry['accounts.index']['types'],
  },
  'accounts.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/accounts/:id',
    tokens: [{"old":"/api/v1/accounts/:id","type":0,"val":"api","end":""},{"old":"/api/v1/accounts/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/accounts/:id","type":0,"val":"accounts","end":""},{"old":"/api/v1/accounts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['accounts.show']['types'],
  },
  'ledger_entries.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/ledger-entries',
    tokens: [{"old":"/api/v1/ledger-entries","type":0,"val":"api","end":""},{"old":"/api/v1/ledger-entries","type":0,"val":"v1","end":""},{"old":"/api/v1/ledger-entries","type":0,"val":"ledger-entries","end":""}],
    types: placeholder as Registry['ledger_entries.index']['types'],
  },
  'ledger_entries.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/ledger-entries/:id',
    tokens: [{"old":"/api/v1/ledger-entries/:id","type":0,"val":"api","end":""},{"old":"/api/v1/ledger-entries/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/ledger-entries/:id","type":0,"val":"ledger-entries","end":""},{"old":"/api/v1/ledger-entries/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['ledger_entries.show']['types'],
  },
  'reconciliation.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/reconciliation',
    tokens: [{"old":"/api/v1/reconciliation","type":0,"val":"api","end":""},{"old":"/api/v1/reconciliation","type":0,"val":"v1","end":""},{"old":"/api/v1/reconciliation","type":0,"val":"reconciliation","end":""}],
    types: placeholder as Registry['reconciliation.index']['types'],
  },
  'reconciliation.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/reconciliation/:id',
    tokens: [{"old":"/api/v1/reconciliation/:id","type":0,"val":"api","end":""},{"old":"/api/v1/reconciliation/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/reconciliation/:id","type":0,"val":"reconciliation","end":""},{"old":"/api/v1/reconciliation/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['reconciliation.show']['types'],
  },
  'reconciliation.upload': {
    methods: ["POST"],
    pattern: '/api/v1/reconciliation/upload',
    tokens: [{"old":"/api/v1/reconciliation/upload","type":0,"val":"api","end":""},{"old":"/api/v1/reconciliation/upload","type":0,"val":"v1","end":""},{"old":"/api/v1/reconciliation/upload","type":0,"val":"reconciliation","end":""},{"old":"/api/v1/reconciliation/upload","type":0,"val":"upload","end":""}],
    types: placeholder as Registry['reconciliation.upload']['types'],
  },
  'reconciliation.match': {
    methods: ["POST"],
    pattern: '/api/v1/reconciliation/match',
    tokens: [{"old":"/api/v1/reconciliation/match","type":0,"val":"api","end":""},{"old":"/api/v1/reconciliation/match","type":0,"val":"v1","end":""},{"old":"/api/v1/reconciliation/match","type":0,"val":"reconciliation","end":""},{"old":"/api/v1/reconciliation/match","type":0,"val":"match","end":""}],
    types: placeholder as Registry['reconciliation.match']['types'],
  },
  'reconciliation.run_reconciliation': {
    methods: ["POST"],
    pattern: '/api/v1/reconciliation/run',
    tokens: [{"old":"/api/v1/reconciliation/run","type":0,"val":"api","end":""},{"old":"/api/v1/reconciliation/run","type":0,"val":"v1","end":""},{"old":"/api/v1/reconciliation/run","type":0,"val":"reconciliation","end":""},{"old":"/api/v1/reconciliation/run","type":0,"val":"run","end":""}],
    types: placeholder as Registry['reconciliation.run_reconciliation']['types'],
  },
  'routing.resolve_provider': {
    methods: ["POST"],
    pattern: '/api/v1/routing/resolve',
    tokens: [{"old":"/api/v1/routing/resolve","type":0,"val":"api","end":""},{"old":"/api/v1/routing/resolve","type":0,"val":"v1","end":""},{"old":"/api/v1/routing/resolve","type":0,"val":"routing","end":""},{"old":"/api/v1/routing/resolve","type":0,"val":"resolve","end":""}],
    types: placeholder as Registry['routing.resolve_provider']['types'],
  },
  'monitoring.get_provider_health': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/monitoring/providers',
    tokens: [{"old":"/api/v1/monitoring/providers","type":0,"val":"api","end":""},{"old":"/api/v1/monitoring/providers","type":0,"val":"v1","end":""},{"old":"/api/v1/monitoring/providers","type":0,"val":"monitoring","end":""},{"old":"/api/v1/monitoring/providers","type":0,"val":"providers","end":""}],
    types: placeholder as Registry['monitoring.get_provider_health']['types'],
  },
  'monitoring.get_queue_stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/monitoring/queues',
    tokens: [{"old":"/api/v1/monitoring/queues","type":0,"val":"api","end":""},{"old":"/api/v1/monitoring/queues","type":0,"val":"v1","end":""},{"old":"/api/v1/monitoring/queues","type":0,"val":"monitoring","end":""},{"old":"/api/v1/monitoring/queues","type":0,"val":"queues","end":""}],
    types: placeholder as Registry['monitoring.get_queue_stats']['types'],
  },
  'new_account.create': {
    methods: ["GET","HEAD"],
    pattern: '/signup',
    tokens: [{"old":"/signup","type":0,"val":"signup","end":""}],
    types: placeholder as Registry['new_account.create']['types'],
  },
  'new_account.store': {
    methods: ["POST"],
    pattern: '/signup',
    tokens: [{"old":"/signup","type":0,"val":"signup","end":""}],
    types: placeholder as Registry['new_account.store']['types'],
  },
  'session.create': {
    methods: ["GET","HEAD"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['session.create']['types'],
  },
  'session.store': {
    methods: ["POST"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['session.store']['types'],
  },
  'session.destroy': {
    methods: ["POST"],
    pattern: '/logout',
    tokens: [{"old":"/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['session.destroy']['types'],
  },
  'admin': {
    methods: ["GET","HEAD"],
    pattern: '/admin',
    tokens: [{"old":"/admin","type":0,"val":"admin","end":""}],
    types: placeholder as Registry['admin']['types'],
  },
  'admin.dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/admin/dashboard',
    tokens: [{"old":"/admin/dashboard","type":0,"val":"admin","end":""},{"old":"/admin/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['admin.dashboard']['types'],
  },
  'admin.applications': {
    methods: ["GET","HEAD"],
    pattern: '/admin/applications',
    tokens: [{"old":"/admin/applications","type":0,"val":"admin","end":""},{"old":"/admin/applications","type":0,"val":"applications","end":""}],
    types: placeholder as Registry['admin.applications']['types'],
  },
  'admin.applications.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/applications/create',
    tokens: [{"old":"/admin/applications/create","type":0,"val":"admin","end":""},{"old":"/admin/applications/create","type":0,"val":"applications","end":""},{"old":"/admin/applications/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['admin.applications.create']['types'],
  },
  'admin.applications.detail': {
    methods: ["GET","HEAD"],
    pattern: '/admin/applications/:appId',
    tokens: [{"old":"/admin/applications/:appId","type":0,"val":"admin","end":""},{"old":"/admin/applications/:appId","type":0,"val":"applications","end":""},{"old":"/admin/applications/:appId","type":1,"val":"appId","end":""}],
    types: placeholder as Registry['admin.applications.detail']['types'],
  },
  'admin.settings': {
    methods: ["GET","HEAD"],
    pattern: '/admin/settings',
    tokens: [{"old":"/admin/settings","type":0,"val":"admin","end":""},{"old":"/admin/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['admin.settings']['types'],
  },
  'admin.applications.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/:id/edit',
    tokens: [{"old":"/admin/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.applications.edit']['types'],
  },
  'admin.users': {
    methods: ["GET","HEAD"],
    pattern: '/admin/:id/users',
    tokens: [{"old":"/admin/:id/users","type":0,"val":"admin","end":""},{"old":"/admin/:id/users","type":1,"val":"id","end":""},{"old":"/admin/:id/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['admin.users']['types'],
  },
  'admin.users.detail': {
    methods: ["GET","HEAD"],
    pattern: '/admin/:id/users/:userId',
    tokens: [{"old":"/admin/:id/users/:userId","type":0,"val":"admin","end":""},{"old":"/admin/:id/users/:userId","type":1,"val":"id","end":""},{"old":"/admin/:id/users/:userId","type":0,"val":"users","end":""},{"old":"/admin/:id/users/:userId","type":1,"val":"userId","end":""}],
    types: placeholder as Registry['admin.users.detail']['types'],
  },
  'admin.providers': {
    methods: ["GET","HEAD"],
    pattern: '/admin/:id/providers',
    tokens: [{"old":"/admin/:id/providers","type":0,"val":"admin","end":""},{"old":"/admin/:id/providers","type":1,"val":"id","end":""},{"old":"/admin/:id/providers","type":0,"val":"providers","end":""}],
    types: placeholder as Registry['admin.providers']['types'],
  },
  'admin.providers.detail': {
    methods: ["GET","HEAD"],
    pattern: '/admin/:id/providers/:providerId',
    tokens: [{"old":"/admin/:id/providers/:providerId","type":0,"val":"admin","end":""},{"old":"/admin/:id/providers/:providerId","type":1,"val":"id","end":""},{"old":"/admin/:id/providers/:providerId","type":0,"val":"providers","end":""},{"old":"/admin/:id/providers/:providerId","type":1,"val":"providerId","end":""}],
    types: placeholder as Registry['admin.providers.detail']['types'],
  },
  'admin.providers.countries.store': {
    methods: ["POST"],
    pattern: '/admin/:id/providers/:providerId/countries/:countryId',
    tokens: [{"old":"/admin/:id/providers/:providerId/countries/:countryId","type":0,"val":"admin","end":""},{"old":"/admin/:id/providers/:providerId/countries/:countryId","type":1,"val":"id","end":""},{"old":"/admin/:id/providers/:providerId/countries/:countryId","type":0,"val":"providers","end":""},{"old":"/admin/:id/providers/:providerId/countries/:countryId","type":1,"val":"providerId","end":""},{"old":"/admin/:id/providers/:providerId/countries/:countryId","type":0,"val":"countries","end":""},{"old":"/admin/:id/providers/:providerId/countries/:countryId","type":1,"val":"countryId","end":""}],
    types: placeholder as Registry['admin.providers.countries.store']['types'],
  },
  'admin.providers.countries.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/:id/providers/:providerId/countries/:countryId',
    tokens: [{"old":"/admin/:id/providers/:providerId/countries/:countryId","type":0,"val":"admin","end":""},{"old":"/admin/:id/providers/:providerId/countries/:countryId","type":1,"val":"id","end":""},{"old":"/admin/:id/providers/:providerId/countries/:countryId","type":0,"val":"providers","end":""},{"old":"/admin/:id/providers/:providerId/countries/:countryId","type":1,"val":"providerId","end":""},{"old":"/admin/:id/providers/:providerId/countries/:countryId","type":0,"val":"countries","end":""},{"old":"/admin/:id/providers/:providerId/countries/:countryId","type":1,"val":"countryId","end":""}],
    types: placeholder as Registry['admin.providers.countries.destroy']['types'],
  },
  'admin.mobile-operators': {
    methods: ["GET","HEAD"],
    pattern: '/admin/:id/mobile-operators',
    tokens: [{"old":"/admin/:id/mobile-operators","type":0,"val":"admin","end":""},{"old":"/admin/:id/mobile-operators","type":1,"val":"id","end":""},{"old":"/admin/:id/mobile-operators","type":0,"val":"mobile-operators","end":""}],
    types: placeholder as Registry['admin.mobile-operators']['types'],
  },
  'admin.mobile-operators.store': {
    methods: ["POST"],
    pattern: '/admin/:id/mobile-operators',
    tokens: [{"old":"/admin/:id/mobile-operators","type":0,"val":"admin","end":""},{"old":"/admin/:id/mobile-operators","type":1,"val":"id","end":""},{"old":"/admin/:id/mobile-operators","type":0,"val":"mobile-operators","end":""}],
    types: placeholder as Registry['admin.mobile-operators.store']['types'],
  },
  'admin.mobile-operators.update': {
    methods: ["PUT"],
    pattern: '/admin/:id/mobile-operators/:operatorId',
    tokens: [{"old":"/admin/:id/mobile-operators/:operatorId","type":0,"val":"admin","end":""},{"old":"/admin/:id/mobile-operators/:operatorId","type":1,"val":"id","end":""},{"old":"/admin/:id/mobile-operators/:operatorId","type":0,"val":"mobile-operators","end":""},{"old":"/admin/:id/mobile-operators/:operatorId","type":1,"val":"operatorId","end":""}],
    types: placeholder as Registry['admin.mobile-operators.update']['types'],
  },
  'admin.mobile-operators.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/:id/mobile-operators/:operatorId',
    tokens: [{"old":"/admin/:id/mobile-operators/:operatorId","type":0,"val":"admin","end":""},{"old":"/admin/:id/mobile-operators/:operatorId","type":1,"val":"id","end":""},{"old":"/admin/:id/mobile-operators/:operatorId","type":0,"val":"mobile-operators","end":""},{"old":"/admin/:id/mobile-operators/:operatorId","type":1,"val":"operatorId","end":""}],
    types: placeholder as Registry['admin.mobile-operators.destroy']['types'],
  },
  'admin.countries': {
    methods: ["GET","HEAD"],
    pattern: '/admin/:id/countries',
    tokens: [{"old":"/admin/:id/countries","type":0,"val":"admin","end":""},{"old":"/admin/:id/countries","type":1,"val":"id","end":""},{"old":"/admin/:id/countries","type":0,"val":"countries","end":""}],
    types: placeholder as Registry['admin.countries']['types'],
  },
  'admin.countries.create': {
    methods: ["POST"],
    pattern: '/admin/:id/countries/create/:iso2',
    tokens: [{"old":"/admin/:id/countries/create/:iso2","type":0,"val":"admin","end":""},{"old":"/admin/:id/countries/create/:iso2","type":1,"val":"id","end":""},{"old":"/admin/:id/countries/create/:iso2","type":0,"val":"countries","end":""},{"old":"/admin/:id/countries/create/:iso2","type":0,"val":"create","end":""},{"old":"/admin/:id/countries/create/:iso2","type":1,"val":"iso2","end":""}],
    types: placeholder as Registry['admin.countries.create']['types'],
  },
  'admin.countries.delete': {
    methods: ["DELETE"],
    pattern: '/admin/:id/countries/:countryId',
    tokens: [{"old":"/admin/:id/countries/:countryId","type":0,"val":"admin","end":""},{"old":"/admin/:id/countries/:countryId","type":1,"val":"id","end":""},{"old":"/admin/:id/countries/:countryId","type":0,"val":"countries","end":""},{"old":"/admin/:id/countries/:countryId","type":1,"val":"countryId","end":""}],
    types: placeholder as Registry['admin.countries.delete']['types'],
  },
  'admin.transactions': {
    methods: ["GET","HEAD"],
    pattern: '/admin/:id/transactions',
    tokens: [{"old":"/admin/:id/transactions","type":0,"val":"admin","end":""},{"old":"/admin/:id/transactions","type":1,"val":"id","end":""},{"old":"/admin/:id/transactions","type":0,"val":"transactions","end":""}],
    types: placeholder as Registry['admin.transactions']['types'],
  },
  'admin.webhooks': {
    methods: ["GET","HEAD"],
    pattern: '/admin/:id/webhooks',
    tokens: [{"old":"/admin/:id/webhooks","type":0,"val":"admin","end":""},{"old":"/admin/:id/webhooks","type":1,"val":"id","end":""},{"old":"/admin/:id/webhooks","type":0,"val":"webhooks","end":""}],
    types: placeholder as Registry['admin.webhooks']['types'],
  },
  'admin.commissions': {
    methods: ["GET","HEAD"],
    pattern: '/admin/:id/commissions',
    tokens: [{"old":"/admin/:id/commissions","type":0,"val":"admin","end":""},{"old":"/admin/:id/commissions","type":1,"val":"id","end":""},{"old":"/admin/:id/commissions","type":0,"val":"commissions","end":""}],
    types: placeholder as Registry['admin.commissions']['types'],
  },
  'admin.routing': {
    methods: ["GET","HEAD"],
    pattern: '/admin/:id/routing',
    tokens: [{"old":"/admin/:id/routing","type":0,"val":"admin","end":""},{"old":"/admin/:id/routing","type":1,"val":"id","end":""},{"old":"/admin/:id/routing","type":0,"val":"routing","end":""}],
    types: placeholder as Registry['admin.routing']['types'],
  },
  'admin.logs': {
    methods: ["GET","HEAD"],
    pattern: '/admin/:id/logs',
    tokens: [{"old":"/admin/:id/logs","type":0,"val":"admin","end":""},{"old":"/admin/:id/logs","type":1,"val":"id","end":""},{"old":"/admin/:id/logs","type":0,"val":"logs","end":""}],
    types: placeholder as Registry['admin.logs']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
